/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basicLibraryNew;

import java.util.*;

public class Library {
    public static void main(String[] args) {
        System.out.println("hello");
        int[]testArray={1,1};
        roll(6);
        containsDuplicates(testArray);
        calculatingAverages(testArray);

        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        arrayOfArrays(weeklyMonthTemperatures);
        arrayOfweather(weeklyMonthTemperatures);
        List<String> value= new ArrayList<>();
        value.add("Bush");
        value.add("Bush");
        value.add("Bush");
        value.add("Shrub");
        value.add("Hedge");
        value.add("Shrub");
        value.add("Bush");
        value.add("Hedge");
        value.add("Bush");
        tally(value);
    }



    public static int[] roll(int n){

        Random randomRoll = new Random();

        int[] arrayOfSide = new int[n];
        int sideOfDice;
        for (int i=0; i<n; i++){
            sideOfDice = randomRoll.nextInt(6);
            arrayOfSide[i]=sideOfDice+1;
            System.out.println(arrayOfSide[i]+",");
        }
        return arrayOfSide;

    }

    public static boolean containsDuplicates(int[] array) {
        return false;
    }

    public static double calculatingAverages (int[] array) {
        double sum = 0;
        for (int value : array) {
            sum += value;
        }
        System.out.println(sum / array.length);
        return sum / array.length;
    }

    public static int[] arrayOfArrays(int[][] array) {
        ArrayList<Double> arrayOfAvg = new ArrayList<>();
        for (int i = 0; i < array.length; i++) {
            double sum = 0;
            for (int j = 0; j < array[i].length; j++) {
                sum += array[i][j];
            }
            arrayOfAvg.add(sum / array[i].length);
        }
        Collections.sort(arrayOfAvg);
        for (int i = 0; i < arrayOfAvg.size() ; i++) {
            System.out.println( "the averages is = " + arrayOfAvg.get(i) );
        }
        System.out.println(" The Lowest Average is: " + arrayOfAvg.get(0) + "\n");
        System.out.println(arrayOfAvg);
        return array[arrayOfAvg.indexOf(Collections.min(arrayOfAvg))];

    }



    public static String arrayOfweather(int [][] arrayOfTemps) {
        System.out.println("\n analyzingWeatherData Method\n");


        Set<Integer> temp = new HashSet<Integer>();

        for (int i = 0; i < arrayOfTemps.length; i++) {
            for (int j = 0; j < arrayOfTemps[i].length; j++) {
                temp.add(arrayOfTemps[i][j]);
            }
        }

        temp = new TreeSet<>(temp);



        Integer[] temperaturesAsAnArray = temp.toArray(new Integer[temp.size()]);

        int high = temperaturesAsAnArray[temperaturesAsAnArray.length-1];
        int low = temperaturesAsAnArray[0];

        System.out.println("\n High: " + high);
        System.out.println("\n Low: " + low);

        System.out.println("\n");

        String tempsNotShown = "";
        for (int i = low; i < high; i++) {
            if(!temp.contains(i)){
                tempsNotShown = "Never saw temperature: " + i;
                System.out.println(tempsNotShown);
            }
        }

        System.out.println(tempsNotShown+"\n");

        return tempsNotShown;
    }
    public static String tally(List<String> value){

        System.out.println(value);

        Set<String> repeatedValues = new HashSet<String>();
        int count = 0;
        for (int i = 0; i < value.size(); i++) {
            System.out.println(value.get(i));
            if(repeatedValues.contains(value.get(i))==true){
                count++;
            } else {
                count = 0;
                repeatedValues.add(value.get(i));
            }
            System.out.println(count);
        }
        System.out.println(repeatedValues);
        String tallyMost = "received the most votes!  "+repeatedValues;
        return tallyMost;
    }


}