/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basicLibraryNew;

import java.util.*;

public class Library {
    public static void main(String[] args) {
        System.out.println("hello");
        int[]testArray={1,1};
        roll(6);
        containsDuplicates(testArray);
        calculatingAverages(testArray);

        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        arrayOfArrays(weeklyMonthTemperatures);

    }

    public static int[] roll(int n){

        Random randomRoll = new Random();

        int[] arrayOfSide = new int[n];
        int sideOfDice;
        for (int i=0; i<n; i++){
            sideOfDice = randomRoll.nextInt(6);
            arrayOfSide[i]=sideOfDice+1;
            System.out.println(arrayOfSide[i]+",");
        }
        return arrayOfSide;

    }

    public static boolean containsDuplicates(int[] array) {
        return false;
    }

    public static double calculatingAverages (int[] array) {
        double sum = 0;
        for (int value : array) {
            sum += value;
        }
        System.out.println(sum / array.length);
        return sum / array.length;
    }

    public static int[] arrayOfArrays(int[][] array) {
        ArrayList<Double> arrayOfAvg = new ArrayList<>();
        for (int i = 0; i < array.length; i++) {
            double sum = 0;
            for (int j = 0; j < array[i].length; j++) {
                sum += array[i][j];
            }
            arrayOfAvg.add(sum / array[i].length);
        }
        Collections.sort(arrayOfAvg);
        for (int i = 0; i < arrayOfAvg.size() ; i++) {
            System.out.println( "the averages is = " + arrayOfAvg.get(i) );
        }
        System.out.println(" The Lowest Average is: " + arrayOfAvg.get(0) + "\n");
        System.out.println(arrayOfAvg);
        return array[arrayOfAvg.indexOf(Collections.min(arrayOfAvg))];

    }

    public static Object arrayOfweather(int[][] array) {
        return null;
    }

    public static Object tally(List<String> votes) {
        return null;
    }
}