/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.util.ArrayList;

public class Library {
    public static void main(String[] args) {
        System.out.println("hello");
        Resturant resturant = new Resturant("mac",4,"5$");

        Shops shops = new Shops("tamara","clothing shop",4);
        Review review = new Review("nice","tamara",3);
        Review review2 = new Review("good","tamara",3);
        System.out.println(review);
        System.out.println(resturant.addReview(review));
        System.out.println(shops.addReview(review));
        shops.addReview(review2);










    }
}
